version: "3"

services:

  appsmith:
    build:
      context: ../../
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    platform: linux/amd64
  auto_update:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check every hour.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup